FROM apache/airflow:2.8.1-python3.11

COPY requirements-airflow.txt /requirements-airflow.txt

RUN pip install --no-cache-dir -r /requirements-airflow.txt

COPY dags /opt/airflow/dags
COPY ingestion /opt/airflow/ingestion
COPY dbt_project /opt/airflow/dbt_project
COPY indexing /opt/airflow/indexing
COPY kibana /opt/airflow/kibana
COPY setup_kibana_dashboard.py /opt/airflow/setup_kibana_dashboard.py

RUN mkdir -p /opt/airflow/data /opt/airflow/dbt_project/logs /opt/airflow/dbt_project/target \
 && chown -R airflow:0 /opt/airflow/dags /opt/airflow/ingestion /opt/airflow/dbt_project \
    /opt/airflow/indexing /opt/airflow/kibana /opt/airflow/setup_kibana_dashboard.py /opt/airflow/data \
 && chmod -R g=u /opt/airflow/dags /opt/airflow/ingestion /opt/airflow/dbt_project \
    /opt/airflow/indexing /opt/airflow/kibana /opt/airflow/data
