FROM apache/airflow:2.8.1-python3.11

COPY requirements-airflow.txt /requirements-airflow.txt

RUN pip install --no-cache-dir -r /requirements-airflow.txt

COPY dags /opt/airflow/dags
COPY ingestion /opt/airflow/ingestion
COPY dbt_project /opt/airflow/dbt_project
COPY indexing /opt/airflow/indexing
COPY kibana /opt/airflow/kibana
COPY setup_kibana_dashboard.py /opt/airflow/setup_kibana_dashboard.py

RUN mkdir -p /opt/airflow/data
