[build]
builder = "DOCKERFILE"
dockerfilePath = "/llm_tracker/railway/Dockerfile.airflow"

[deploy]
startCommand = "/bin/bash /opt/airflow/airflow-scheduler-start.sh"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
