FROM docker.elastic.co/kibana/kibana:8.12.0

COPY railway/kibana-start.sh /usr/local/bin/kibana-start.sh
USER root
RUN chmod +x /usr/local/bin/kibana-start.sh
USER kibana

CMD ["/usr/local/bin/kibana-start.sh"]
